# Generated by Django 2.1.7 on 2019-03-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=255)),
                ('creatorEmail', models.CharField(max_length=255)),
            ],
        ),
    ]
