# Generated by Django 2.1.7 on 2019-03-21 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=255)),
                ('recipeCreator', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepNumber', models.IntegerField()),
                ('stepDescription', models.TextField()),
                ('dishName', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='food.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dishName',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='food.Recipe'),
        ),
    ]
